# Generated by Django 3.1.1 on 2020-10-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201006_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AltaUsuario',
            new_name='Usuario',
        ),
    ]
